name: Generate Snake
# Controls when the action will run
on:
  schedule:
    # Runs every 18 hours
    - cron: "0 */18 * * *"  # Fixed cron syntax
  # Allows manual workflow execution
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks out repository
      - uses: actions/checkout@v3  # Updated to v3
      
      # Generates the snake animation
      - uses: Platane/snk@v3  # Updated to v3
        id: snake-gif
        with:
          github_user_name: Thisarahetz
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg
      
      # Shows the status for debugging
      - run: git status
      
      # Pushes changes to the output branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
      
      # Deploys to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4  # Updated to v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
